workspace:
  base: /go/src
  path: github.com/appleboy/go-spgateway

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: appleboy/golang-testing:1.9
    commands:
      - make vet
      - make lint
      - make embedmd
      - make test

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - coverage.txt

  facebook:
    image: appleboy/drone-facebook
    pull: true
    to: 1234973386524610
    secrets: [ fb_page_token, fb_verify_token ]
    when:
      status: [ changed, failure ]
